from collections.abc import Hashable, Iterable
from typing import Any, Protocol

__all__ = ['Component', 'ComponentID', 'DomainID', 'EntityID', 'Property',
           'RegistryError', 'UnknownArchetypeError', 'UnknownComponentError',
           'UnknownEntityError', 'UnknownSystemError', 'add_component',
           'add_components', 'add_system', 'add_system_to_domain',
           'add_to_archetype', 'cid_of_comp', 'cids_of_eid',
           'clear_properties', 'comp_of_eid', 'comps_of_archetype',
           'comps_of_eid', 'create_archetype', 'create_entity', 'eid_has',
           'eid_of_comp', 'eids_by_cids', 'eids_by_property', 'has',
           'has_property', 'healthcheck', 'purge_by_property',
           'remove_archetype', 'remove_component', 'remove_entity',
           'remove_from_archetype', 'remove_property', 'remove_system',
           'remove_system_from_domain', 'reset', 'run_all_systems',
           'run_domain', 'run_system', 'set_properties', 'set_property',
           'update_component',]


type EntityID = Hashable
type ComponentID = Hashable
type DomainID = Hashable
type Property = Hashable
type Component = object


# The typehinting system can't work with functions using *args, **kwargs.
# This solution comes from https://docs.python.org/3/library/typing.html#annotating-callable-objects
class SystemFunction(Protocol):
    def __call__(self, dt: float, eid: EntityID, *cids: ComponentID, **kwargs: dict[str, object]) -> Any: ...


type RunSystemResult = dict[EntityID, Any]
type EntityComponentsBundle = tuple[EntityID, list[Component]]
type OptionalProperties = Iterable[Property] | None


class UnknownEntityError(Exception): ...
class UnknownComponentError(Exception): ...
class UnknownSystemError(Exception): ...
class UnknownArchetypeError(Exception): ...


class RegistryError(Exception):
    def __init__(self,
                 error: str,
                 *,
                 eid: EntityID,
                 cid: ComponentID | None = None,
                 component: object | None = None,
                 other: object | None = None,
                 properties: OptionalProperties = None) -> None: ...


def reset() -> None: ...
def healthcheck() -> bool: ...


def create_entity(tag: EntityID = None,
                  components: dict[ComponentID, Component] | None = None,
                  properties: OptionalProperties = None) -> EntityID: ...


def remove_entity(eid: EntityID) -> None: ...
def add_component(eid: EntityID, cid: ComponentID, comp: Component) -> ComponentID: ...


update_component = add_component


def add_components(eid: EntityID, components: dict[ComponentID, Component]) -> list[ComponentID]: ...
def remove_component(eid: EntityID, *cids: ComponentID) -> None: ...
def add_system(fkt: SystemFunction, *cids: ComponentID) -> None: ...
def remove_system(fkt: SystemFunction) -> None: ...
def add_system_to_domain(domain: DomainID, system: SystemFunction) -> None: ...
def remove_system_from_domain(domain: DomainID, system: SystemFunction) -> None: ...
def has(eid: EntityID, has_properties: OptionalProperties = None) -> bool: ...


is_eid = has


def eid_has(eid: EntityID, *cids: ComponentID) -> bool: ...
def eids_by_cids(*cids: ComponentID, has_properties: OptionalProperties = None) -> list[tuple[EntityID, list[Component]]]: ...
def cids_of_eid(eid: EntityID) -> list[ComponentID]: ...
def comps_of_eid(eid: EntityID, *cids: ComponentID) -> list[Component]: ...
def comp_of_eid(eid: EntityID, cid: ComponentID) -> Component: ...
def eid_of_comp(comp: Component) -> set(EntityID): ...
def cid_of_comp(eid: EntityID, comp: Component) -> ComponentID: ...


def run_system(dt: float,
               fkt: SystemFunction,
               *cids: ComponentID,
               has_properties: OptionalProperties = None,
               **kwargs: dict[str, Any]) -> RunSystemResult: ...


def run_all_systems(dt: float) -> dict[SystemFunction, RunSystemResult]: ...
def run_domain(dt: float, domain: DomainID) -> dict[SystemFunction, RunSystemResult]: ...
def create_archetype(*cids: ComponentID) -> None: ...
def remove_archetype(cids: Iterable[ComponentID]) -> None: ...
def add_to_archetype(eid: EntityID) -> None: ...
def remove_from_archetype(eid: EntityID, cid: ComponentID | None = None) -> None: ...
def comps_of_archetype(*cids: ComponentID, has_properties: OptionalProperties = None) -> list[EntityComponentsBundle]: ...
def set_property(eid: EntityID, property: Property) -> None: ...
def set_properties(eid: EntityID, properties: Iterable[Property]) -> None: ...
def has_property(eid: EntityID, prop: Property) -> bool: ...
def remove_property(eid: EntityID, prop: Property) -> None: ...
def clear_properties(eid: EntityID) -> None: ...
def eids_by_property(*properties: Property) -> list[EntityID]: ...
def purge_by_property(*properties: Property) -> None: ...
